### ISSUE TITLE
Validators table does not force unique constraint on validation_public_key

### ISSUE THREAD

**Issue by stevenzeiler** [ripple/validator-registry-api#6]

**Comment by wilsonianb** [comment]
If the same domain can operate multiple validators but a validator can only correspond to a single domain, then we can just require `validation_public_key` to be unique.

**Comment by stevenzeiler** [comment]
Good point, the issue is updated.

**Comment by wilsonianb** [comment]
I'm on it and #7

**Comment by wilsonianb** [comment]
Fixed in https://github.com/ripple/validator-registry-api/pull/5
